/**
 * Illustrated book writer — Gemini turns a concept into a book spec:
 * cover, 4-6 chapters of short prose with matching illustration prompts.
 */

import { GoogleGenAI } from "@google/genai";

export interface BookChapter {
  title: string;       // 2-6 words
  prose: string;       // 80-160 words of narrative text
  imagePrompt: string; // 30-60 words for Imagen
}

export interface BookSpec {
  title: string;            // 2-6 words, used as filename
  subtitle: string;
  author_byline: string;    // generated byline, e.g. "Stories by Tekaida"
  coverPrompt: string;      // 30-60 words for the cover illustration
  chapters: BookChapter[];
}

const SYSTEM_PROMPT = `You are an illustrated children's-book / short-story author. Turn the user's
concept into strict JSON — no prose outside the JSON, no code fences. Schema:

{
  "title": string,                       // 2-6 words; will be the filename
  "subtitle": string,                    // one tagline sentence
  "author_byline": string,               // e.g. "Stories by Tekaida"
  "coverPrompt": string,                 // 30-60 words, illustration prompt for the cover
  "chapters": [                          // 4-6 chapters
    {
      "title": string,                   // 2-6 words
      "prose": string,                   // 80-160 words of vivid narrative text
      "imagePrompt": string              // 30-60 words for the chapter illustration
    }
  ]
}

Style: vivid sensory writing, present tense, accessible vocabulary. Image prompts should
specify: subject + action + setting + lighting + art style. Prefer "watercolor",
"flat illustration", "storybook", "cinematic painting" art styles to keep the book
visually consistent.

Avoid named celebrities, trademarked characters, real brands, alcohol, or violence.`;

export async function writeBook(opts: {
  concept: string;
  chapterCount?: number;
  model?: string;
}): Promise<BookSpec> {
  const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY is not set");

  const client = new GoogleGenAI({ apiKey });
  const chapters = Math.min(Math.max(opts.chapterCount ?? 5, 3), 8);

  const resp = await client.models.generateContent({
    model: opts.model || process.env.GEMINI_MODEL || "gemini-2.5-pro",
    contents: `Concept: ${opts.concept}\n\nReturn ${chapters} chapters total.`,
    config: {
      systemInstruction: SYSTEM_PROMPT,
      responseMimeType: "application/json",
    },
  });

  const text = (resp.text ?? "").trim();
  const cleaned = text
    .replace(/^```(?:json)?\s*/, "")
    .replace(/\s*```$/, "")
    .trim();
  const data = JSON.parse(cleaned) as BookSpec;
  if (!data?.chapters?.length || !data.coverPrompt) {
    throw new Error("Book writer returned invalid JSON.");
  }
  return data;
}
